name: Sudoku Bot

on:
  issues:
    types: [opened]

jobs:
  process-sudoku-move:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt || true

    - name: Run sudoku update script
      run: python sudoku_bot.py
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        git config user.name "sudoku-bot"
        git config user.email "sudoku-bot@users.noreply.github.com"

        git add README.md

        git commit -m "Update sudoku board from issue #${{ github.event.issue.number }}" || echo "Nothing to commit"

        git pull --no-rebase || echo "Pull failed, continue"
        
        git push
      continue-on-error: true

    - name: Close issue
      uses: peter-evans/close-issue@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: |
          ✅ 已处理该步棋。
